baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'dsalgo'

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = 'rose-pine-dawn'

[params.meta]
  favicon = false
